service: text

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-2
  memorySize: 128
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:${opt:region, self:provider.region}:*:function:*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DDB_TABLE}"
  environment:
    LANGUAGE: ko
    DDB_TABLE: ${self:service}-${self:provider.environment.LANGUAGE}-${opt:stage, self:provider.stage}
    FX_PREFIX: ${self:service}-${opt:stage, self:provider.stage}
    S3_BUCKET: serverless-${self:service}

functions:
  getTexts:
    handler: functions/text/get.getTexts
    events:
      - http:
          path: texts
          method: get
          cors: true
  createId:
    handler: functions/text/create-id.createId
    events:
      - http:
          path: texts/{id}
          method: post
          cors: true
  updateId:
    handler: functions/text/create-id.createId
    events:
      - http:
          path: texts/{id}
          method: put
          cors: true
  deleteId:
    handler: functions/text/delete-id.deleteId
    events:
      - http:
          path: texts/{id}
          method: delete
          cors: true
  createJson:
    handler: functions/text/create-json.createJson
    events:
      - http:
          path: texts/json
          method: post
          cors: true
  upload:
    handler: functions/common/upload.upload

resources:
  Resources:
    TextsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DDB_TABLE}
    TextsS3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        AccessControl: PublicRead

# you can add packaging information here
#package:
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

